### ISSUE TITLE
[ValueError@interferencegraph.py:62] ValueError: The given set of variables is not an independent set. At least two variables interfere!


### ISSUE THREAD

**Issue by mm4rks** [fkie-cad/dewolf#245]
# What happened?

```python
  File &quot;/opt/dewolf/decompiler/util/bugfinder/bugfinder.py&quot;, line 164, in iter_function_reports
    task_result = self.decompile(function, options)
  File &quot;/opt/dewolf/decompile.py&quot;, line 51, in decompile
    pipeline.run(task)
  File &quot;/opt/dewolf/decompiler/pipeline/pipeline.py&quot;, line 109, in run
    raise e
  File &quot;/opt/dewolf/decompiler/pipeline/pipeline.py&quot;, line 102, in run
    instance.run(task)
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/outofssatranslation.py&quot;, line 83, in run
    self._out_of_ssa()
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/outofssatranslation.py&quot;, line 101, in _out_of_ssa
    self.out_of_ssa_strategy[self._optimization](self)
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/outofssatranslation.py&quot;, line 142, in _lift_minimal_out_of_ssa
    MinimalVariableRenamer(self.task, self.interference_graph).rename()
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/variable_renaming.py&quot;, line 262, in __init__
    super().__init__(task, interference_graph)
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/variable_renaming.py&quot;, line 95, in __init__
    self._contract_variables_that_need_same_name()
  File &quot;/opt/dewolf/decompiler/pipeline/ssa/variable_renaming.py&quot;, line 179, in _contract_variables_that_need_same_name
    self.interference_graph.contract_independent_set(connected_component)
  File &quot;/opt/dewolf/decompiler/structures/interferencegraph.py&quot;, line 62, in contract_independent_set
    raise ValueError(f&quot;The given set of variables is not an independent set. At least two variables interfere!&quot;)

```

Error class `ValueError@interferencegraph.py:62` contains **1176** cases.

# How to reproduce?

```bash
python decompile.py f70d9c140d39f45a63ea704e172d3e7e7fc3394bfc7bf72fe50c9bc8211cc2a0 sub_4031b4 --debug
```

sample: [f70d9c140d39f45a63ea704e172d3e7e7fc3394bfc7bf72fe50c9bc8211cc2a0](https://bugfinder.seclab-bonn.de/download/f70d9c140d39f45a63ea704e172d3e7e7fc3394bfc7bf72fe50c9bc8211cc2a0)
dewolf commit: 5566666af0d3271618e758808fbc7be92be02e1d
Binaryninja version: `3.4.4271`

**Comment by ebehner** [comment]
The error seems to be in expression-propagation memory. Before this stage the cfg looks as follows, the interesting rows are marked:
![image](https://github.com/fkie-cad/dewolf/assets/7224664/bfe1babc-2186-4101-8020-24956e95b866)

Expression-propagation memory propagates the assignment `rdx#1 = &(var_f4#0)` into instruction `0x205e81(0x0, arg2#0, rdx#1, rcx#0)`. See the following picture:
![image](https://github.com/fkie-cad/dewolf/assets/7224664/2103cfbf-8887-4c91-a055-d0961dd535b9)

Next, identity elimination identifies the variables `var_f4#1` and `var_f4#0` because they always have the same value.
The resulting cfg looks as follows:
![image](https://github.com/fkie-cad/dewolf/assets/7224664/2a9f7790-9b76-493e-8fb6-18f272bbd2f0)

The problem is, that after this transformation, the variable `var_f4#0` interfere with the variables `var_f4#3`, but they need to get the same name due to the relation `var_f4#3 -> varHf4#0`. 

We should not propagate a variable over a relation with the same name.

**Comment by NeoQuix** [comment]
Currently the bug finder does not work, therefore I can't test the mentioned sample.
I have another [one](https://github.com/fkie-cad/dewolf/files/15096193/hello_world.tar.gz) (main.main), where the issue only happens on BNinja 3.5 with the new lifter.

**Comment by NeoQuix** [comment]
Tested the new PR for #192 but it did not work.
If the code is modified to not allow any alias variable to be propagated it will work.
So at least we know it's an aliased variable that produces the error.

**Comment by NeoQuix** [comment]
Fixed the PR to use all relations for the same var (ignoring SSA). 
Solves the problem for f70d9c140d39f45a63ea704e172d3e7e7fc3394bfc7bf72fe50c9bc8211cc2a0 and the hello_world go in bninja 3.5.

Issue #192 still fails.
