### ISSUE TITLE
Decompiled code contains undefined variables

### ISSUE THREAD

**Issue by mari-mari** [fkie-cad/dewolf#321]
### What happened?

`var_0` is undefined for some reason.

```c
long _start(long arg1, long arg2, void() * arg3) {
    void var_2;
    long var_3;
    var_3 = var_0;
    __libc_start_main(main, var_1, /* envp) */ &var_2, __libc_csu_init, /* ubp_av */ __libc_csu_fini, /* init)() */ arg3, /* fini)() */ &var_3);
}
```

### How to reproduce?

`python decompile.py forkingserver _start`

[forkingserver.zip](https://github.com/fkie-cad/dewolf/files/12378818/forkingserver.zip)

### Affected Binary Ninja Version(s)

3.4.4271

**Comment by mari-mari** [comment]
FYI @martinclauss

**Comment by NeoQuix** [comment]
That`s a good one. 

After looking at the `LocalDeclarationGenerator` in the backend, it seems like it does not collect all variables inside the code and therefore fails. 
Now the funny part: For Hungarian notation I used the same visitor, and it collects all variables used, yay. 
The problem are the overwrites, which result in wrongful collection. 

Also `var_0` is not defined as well.

**Comment by NeoQuix** [comment]
After updating the `LocalDeclarationGenerator` i get the following code:

```C
ong _start(long arg1, long arg2, void() * arg3) {
    void var_2;
    long var_0;
    long var_3;
    void * var_1;
    var_3 = var_0;
    __libc_start_main(main, var_1, /* envp) */ &var_2, 0UL, /* ubp_av */ 0UL, /* init)() */ arg3, /* fini)() */ &var_3);
}
```

Which at least defines all variables. 
The code is still wrong, but i think we can't really fix it because it goes beyond the scope of the decompiler:
- `var_2` is the same as `arg_8` in bninja, which is a parameter on the stack beyond the scope of `_start` (e.g. at offset +0x08) 
- `var_1` is the same as `__return_addr` , which is literaly the return addr on the stack

Will look shortly into the lifter to see if there is a way to get these information

**Comment by NeoQuix** [comment]
Lifting of all variables is correct. 
Out-of-ssa renames/changes both variables from their original names into the ones in the output. 
Will look into it later

**Comment by NeoQuix** [comment]
NVM, wasted a whole hour of my time because i misread one thing....yay
Will look at it later...

**Comment by NeoQuix** [comment]
Explanation: `_start` has it's own set of rules for registers/stack which kinda destroy some assumptions we make. 
At the start of `_start` only the registers `rdx` and `rsp` contain valid values + the stack has `argc, argv, env` at the stack outside of the scope of `_start`.

Two variables don't have a definition because:
- `var_0` (`rax` in bninja), is not defined, it just has arbitrary data, which `_start` uses to align the stack to 16Byte.
- `var_1` (`return_addr`) is renamed and does not have a definition (is used to get argc from the stack)
- `var_2` (`arg_8`) is a pointer to `ubp_av` (argv) which is just the argv pointer which is "out of the scope of start". 

For a more detailed [look](https://0xax.gitbooks.io/linux-insides/content/Misc/linux-misc-4.html)

**Comment by NeoQuix** [comment]
Conclusion: This will NOT be fixed
